#!/bin/sh
#./bib-grow < seed.bib | bibtool --preserve.key.case=on > library.bib
./bib-grow < seed.bib > library.bib
bibtex2html -s alpha -a \
        -f txt -f ee \
        -nf pdf '.pdf (remote)' -nf file '.pdf (cached)' \
        -nf amazon Amazon \
        -nf arxiv arXiv \
        -nf citeseerx CiteSeerX \
        -nf dblp DBLP \
        -nf euclid 'Project Euclid' \
        -nf gbooks 'Google Books' \
        -nf jstor JSTOR \
        -nf worldcat WorldCat \
        library.bib
