#!/usr/bin/env python

import sys
import time
from util import *

scheme = sys.argv[1]
fname  = sys.argv[2]

if scheme == 'doi': service = 'crossref'
else:               service = scheme

def entry_plain(entry):
    l = []
    for p in entry.persons['author']:
        l.append(' '.join(p.last()))
    if 'year' in entry.fields:
        l.append(entry.fields['year'])
    l.append(entry.fields['title'])
    return str_norm(' '.join(l))

with open(fname,'r') as f: bib = parse_bib(f)
for key,entry in bib.entries.items():
    if entry.type == 'book': continue
    if scheme not in entry.fields:
        if 'author' not in entry.persons: continue
        plain = entry_plain(entry); print key, plain
        entry.fields[scheme] = 'none' # avoid trying to fill again later
        results = list(bib_search(service, plain))
        for uri,title,desc in results:
            id = uri[len(scheme + ':'):]
            if len(results) == 1 or streq_norm(title, entry.fields['title']):
                print '[%s] %s\n  %s' % (uri,title,desc)
                entry.fields[scheme] = id; break
        with open(fname,'w') as f: write_bib(bib, f)
        time.sleep(1)
